// ============================================================================
// Generated from t27 spec: IglaMvpTernaryClassifier
// DO NOT EDIT - generated by t27c gen-verilog
// phi^2 + 1/phi^2 = 3 | TRINITY
// ============================================================================

`timescale 1ns / 1ps
`default_nettype none

module IglaMvpTernaryClassifier (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        en,
    input  wire [7:0] x,
    output wire        ready,
    output wire [7:0] result
);

    // -------------------------------------------------------
    // Parameters (from const declarations)
    // -------------------------------------------------------
    localparam [7:0] GFT_ZERO = 0;
    localparam [7:0] GFT_POS = 1;
    localparam [7:0] GFT_NEG = 2;
    localparam [7:0] N_INPUTS = 8;
    localparam [7:0] N_CLASSES = 3;
    localparam [7:0] N_WEIGHTS = 24;
    localparam [15:0] W_A = 661;
    localparam [15:0] W_B = 2392;
    localparam [15:0] W_C = 22144;

    // -------------------------------------------------------
    // R-SI-1: multiplication helper (no `*` operator)
    // -------------------------------------------------------
    function [63:0] __mul_noop; // t27#1886: 64-bit, u64 products no longer truncate
        input [63:0] a;
        input [63:0] b;
        integer i;
        reg [127:0] acc;
        begin
            acc = 128'd0;
            for (i = 0; i < 64; i = i + 1) begin
                if (b[i]) acc = acc + ({64'd0, a} << i);
            end
            __mul_noop = acc[63:0];
        end
    endfunction

    assign ready = 1'b1;

    // -------------------------------------------------------
    // Combinational logic (from function declarations)
    // -------------------------------------------------------

    // function: weight_at
    function [7:0] weight_at; // -> u8
        input [15:0] tmpl;
        input [7:0] i;
        begin : weight_at_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            weight_at = (((tmpl >> __mul_noop(i, 2)) & 3) & {8{1'b1}});
            __t27_ret = 1'b1;
        end
    endfunction

    // function: contrib
    function signed [31:0] contrib; // -> i32
        input [7:0] code;
        input [7:0] x;
        begin : contrib_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            if ((code == GFT_POS)) begin
                contrib = $signed(x);
                __t27_ret = 1'b1;
            end else if ((code == GFT_NEG)) begin
                contrib = (0 - $signed(x));
                __t27_ret = 1'b1;
            end else begin
                contrib = 0;
                __t27_ret = 1'b1;
            end
        end
    endfunction

    // function: bit_at
    function [7:0] bit_at; // -> u8
        input [7:0] x;
        input [7:0] i;
        begin : bit_at_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            bit_at = ((x >> i) & 1);
            __t27_ret = 1'b1;
        end
    endfunction

    // function: score
    function signed [31:0] score; // -> i32
        input [15:0] tmpl;
        input [7:0] x;
        begin : score_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            score = (((((((contrib(weight_at(tmpl, 0), bit_at(x, 0)) + contrib(weight_at(tmpl, 1), bit_at(x, 1))) + contrib(weight_at(tmpl, 2), bit_at(x, 2))) + contrib(weight_at(tmpl, 3), bit_at(x, 3))) + contrib(weight_at(tmpl, 4), bit_at(x, 4))) + contrib(weight_at(tmpl, 5), bit_at(x, 5))) + contrib(weight_at(tmpl, 6), bit_at(x, 6))) + contrib(weight_at(tmpl, 7), bit_at(x, 7)));
            __t27_ret = 1'b1;
        end
    endfunction

    // function: score_a
    function signed [31:0] score_a; // -> i32
        input [7:0] x;
        begin : score_a_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            score_a = score(W_A, x);
            __t27_ret = 1'b1;
        end
    endfunction

    // function: score_b
    function signed [31:0] score_b; // -> i32
        input [7:0] x;
        begin : score_b_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            score_b = score(W_B, x);
            __t27_ret = 1'b1;
        end
    endfunction

    // function: score_c
    function signed [31:0] score_c; // -> i32
        input [7:0] x;
        begin : score_c_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            score_c = score(W_C, x);
            __t27_ret = 1'b1;
        end
    endfunction

    // function: classify
    function [7:0] classify; // -> u8
        input [7:0] x;
        begin : classify_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            if (((score_a(x) >= score_b(x)) && (score_a(x) >= score_c(x)))) begin
                classify = 0;
                __t27_ret = 1'b1;
            end else if ((score_b(x) >= score_c(x))) begin
                classify = 1;
                __t27_ret = 1'b1;
            end else begin
                classify = 2;
                __t27_ret = 1'b1;
            end
        end
    endfunction

    // function: on_comb
    function [7:0] on_comb; // -> u8
        input [7:0] x;
        begin : on_comb_body
            reg __t27_ret;
            __t27_ret = 1'b0;
            on_comb = classify(x);
            __t27_ret = 1'b1;
        end
    endfunction

    assign result = on_comb(x);
    // -------------------------------------------------------
    // NOT LOWERED BY THIS BACKEND
    //
    // `gen-verilog` emits synthesizable RTL. A test, an invariant and a
    // bench are simulation constructs -- yosys turns each `$display` into a
    // `$print` cell and nextpnr has no BEL to place one. They are carried by
    // `gen-verilog-for-simulation`, which lowers every declaration below.
    //
    // test      weight_a0_is_pos
    // test      weight_a3_is_neg
    // test      weight_a5_is_zero
    // test      weight_b1_is_neg
    // test      weight_c7_is_pos
    // test      pos_weight_passes_a_set_bit
    // test      neg_weight_negates_a_set_bit
    // test      zero_weight_is_a_skip
    // test      any_weight_on_a_clear_bit_is_zero
    // test      score_a_of_7
    // test      score_b_of_7
    // test      score_c_of_7
    // test      score_a_of_60
    // test      score_b_of_60
    // test      score_c_of_224
    // test      score_a_of_255
    // test      score_b_of_24
    // test      score_c_of_240
    // test      classify_0_is_class_0
    // test      classify_7_is_class_0
    // test      classify_60_is_class_1
    // test      classify_224_is_class_2
    // test      classify_255_ties_to_class_0
    // test      classify_3_is_class_0
    // test      classify_24_is_class_1
    // test      classify_192_is_class_2
    // test      classify_15_is_class_0
    // test      classify_240_is_class_2
    // test      comb_surface_classifies_left
    // test      comb_surface_classifies_middle
    // test      comb_surface_classifies_right
    // invariant gft_zero_matches_canonical
    // invariant gft_pos_matches_canonical
    // invariant gft_neg_matches_canonical
    // invariant weight_count_is_inputs_times_classes
    // invariant eight_inputs
    // invariant three_classes
    // invariant a_template_fits_sixteen_bits
    // invariant templates_a_and_b_differ
    // invariant templates_b_and_c_differ
    // invariant templates_a_and_c_differ
    // -------------------------------------------------------

endmodule

`default_nettype wire
